# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: image_stream.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'image_stream.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12image_stream.proto\x12\x07openbot\"\x0e\n\x0cImageRequest\"8\n\nImageChunk\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x0b\n\x03seq\x18\x02 \x01(\x05\x12\x0f\n\x07is_last\x18\x03 \x01(\x08\x32R\n\x12ImageStreamService\x12<\n\x0cStreamImages\x12\x15.openbot.ImageRequest\x1a\x13.openbot.ImageChunk0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'image_stream_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGEREQUEST']._serialized_start=31
  _globals['_IMAGEREQUEST']._serialized_end=45
  _globals['_IMAGECHUNK']._serialized_start=47
  _globals['_IMAGECHUNK']._serialized_end=103
  _globals['_IMAGESTREAMSERVICE']._serialized_start=105
  _globals['_IMAGESTREAMSERVICE']._serialized_end=187
# @@protoc_insertion_point(module_scope)
